### ISSUE TITLE
Problem creating vm 

### ISSUE THREAD

**Issue by selund** [ace13/foreman_hyperv#14]
I'm trying to get this to work in our environment, but at the moment I get a bit strange error. 

"Oops, we're sorry but something went wrong getaddrinfo: Name or service not known (CH1BLADE1SLOT0.255.30.111:5985)"  

Ok, the fact that foreman can't find the address is quite understandable, but as to how that address gets created I don't understand. The hostname is   CH1BLADE1SLOT0 , and the ip is 10.255.30.111, so it seems that the first octet of the ip address somehow gets truncated. 

I can attach the stack trace, but I'm uncertain how much help it would be as I suspect the problem is not where it's triggered. 

The version of foreman is 1.15.6 and foreman_hyperv was pulled from git on friday. Is there anything else I can provide to find out what's going on?

**Comment by ace13** [comment]
That sounds like a really strange error, I don't do any type of manual IP lookup anywhere as far as I know. Though I guess an issue might occur if trying to use my naïve cluster command routing without proper DNS names.

How does your Compute Resource configuration look?

**Comment by selund** [comment]
I'm using ip address for the resource url. I'll try to use the dns name tomorrow, and see if that helps. Thanks for the advice.

**Comment by ace13** [comment]
> Hmm, thinking about it, could it be that there is a function somewhere that takes the resource url, and splits in into (host,domain) using the first '.' as a separator, and when you use one node in the cluster it adds nodename.domain, as the address it tries to work with?

Like I said, probably an issue with my naïve cluster command router. 😅
Really need to rethink that whole thing, but it was a simple way to get something that would run and not explode the moment there was another machine available on the cluster.

**Comment by selund** [comment]
Using fqdn for the winRM endpoint solved the problem for me. 
Add a comment to use fqdn and close the ticket?

**Comment by ace13** [comment]
I mean, there only reason why IPs can't be used is due to a hack for doing direct connections to clustered machines, but I guess that would be better done through a new issue instead of leaving this one about.

I'll just throw in a disclaimer for now then.
