### ISSUE TITLE
foreman_hyperv

### ISSUE THREAD

**Issue by eevans6913** [ace13/foreman_hyperv#24]
Environment CentOS 8 x64
Hosted on Ovirt 4.3 CentOS 7
CPU 2
Ram 16 GB
Foreman 2.4 
Katello 4.0

I have Hyperv as a compute resource in Foreman but cannot list vm's. I get the following error when trying to view vm's
```
There was an error listing VMs: Unable to parse authorization header. Headers: {"Content-Type"=>"text/html; charset=us-ascii", "Server"=>"Microsoft-HTTPAPI/2.0", "Date"=>"Thu, 24 Jun 2021 19:18:31 GMT", "Connection"=>"close", "Content-Length"=>"315"} Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd"> <HTML><HEAD><TITLE>Not Found</TITLE> <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD> <BODY><h2>Not Found</h2> <hr><p>HTTP Error 404. The requested resource is not found.</p> </BODY></HTML> (404).
```

Foreman-rake console

```
[root@katello ~]# foreman-rake console
Loading production environment (Rails 6.0.3.4)
irb(main):001:0> cr = Compute Resource.find_by name: 'HV01'
Traceback (most recent call last):
        2: from lib/tasks/console.rake:5:in `block in <top (required)>'
        1: from (irb):1
NameError (uninitialized constant Resource)
irb(main):002:0> cr = Compute Resource.find_by name: 'HV02'
Traceback (most recent call last):
        2: from lib/tasks/console.rake:5:in `block in <top (required)>'
        1: from (irb):2
NameError (uninitialized constant Resource)
irb(main):003:0> cr = Compute Resource.find_by name: 'HV02.digitaldatatechs.com'
Traceback (most recent call last):
        2: from lib/tasks/console.rake:5:in `block in <top (required)>'
        1: from (irb):3
NameError (uninitialized constant Resource)
irb(main):004:0> cr = Compute Resource.find_by name: '192.168.254.230'          Traceback (most recent call last):
        2: from lib/tasks/console.rake:5:in `block in <top (required)>'
        1: from (irb):4
NameError (uninitialized constant Resource)
irb(main):005:0>
```
Hyper-V config:
```
winrm winrm/config/listener

Listener [Source="GPO"]
    Address = *
    Transport = HTTP
    Port = 5985
    Hostname
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint
    ListeningOn = 192.168.254.230

Listener
    Address = *
    Transport = HTTPS
    Port = 5986
    Hostname = HV02
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint = D442460344F2154D02546EFCA3E5788ACDCD327B
    ListeningOn = 192.168.254.230

Listener [Source="Compatibility"]
    Address = *
    Transport = HTTP
    Port = 80
    Hostname
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint
    ListeningOn = 192.168.254.230

PS C:\Users\Administrator.DIGITALDATATECH>  winrm get winrm/config
Config
    MaxEnvelopeSizekb = 500
    MaxTimeoutms = 60000
    MaxBatchItems = 32000
    MaxProviderRequests = 4294967295
    Client
        NetworkDelayms = 5000
        URLPrefix = wsman
        AllowUnencrypted = false
        Auth
            Basic = true
            Digest = true
            Kerberos = true
            Negotiate = true
            Certificate = true
            CredSSP = true
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        TrustedHosts = *
    Service
        RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)(A;;GR;;;IU)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;WD)
        MaxConcurrentOperations = 4294967295
        MaxConcurrentOperationsPerUser = 1500
        EnumerationTimeoutms = 240000
        MaxConnections = 300
        MaxPacketRetrievalTimeSeconds = 120
        AllowUnencrypted = true [Source="GPO"]
        Auth
            Basic = true [Source="GPO"]
            Kerberos = true [Source="GPO"]
            Negotiate = true [Source="GPO"]
            Certificate = false
            CredSSP = true [Source="GPO"]
            CbtHardeningLevel = Relaxed [Source="GPO"]
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        IPv4Filter = 192.168.254.1-192.168.254.254 [Source="GPO"]
        IPv6Filter [Source="GPO"]
        EnableCompatibilityHttpListener = true [Source="GPO"]
        EnableCompatibilityHttpsListener = false
        CertificateThumbprint
        AllowRemoteAccess = true [Source="GPO"]
    Winrs
        AllowRemoteShellAccess = true [Source="GPO"]
        IdleTimeout = 900000 [Source="GPO"]
        MaxConcurrentUsers = 5 [Source="GPO"]
        MaxShellRunTime = 2147483647
        MaxProcessesPerShell = 2147483647
        MaxMemoryPerShellMB = 2147483647
        MaxShellsPerUser = 2147483647
```

I can remote manage with powershell and connect-wsman gives a login prompt but does not login. I'm honestly not sure if it's supposed to.,

You seem to be the only one with a grasp of Foreman and hyperv.
I just need some direction.
Thanks.

**Comment by ananace** [comment]
Just a check; the `fog` part of the plugin has a [troubleshooting section](https://github.com/ananace/fog-hyperv#troubleshooting), is any of that relevant?

And if you want to look up the compute resource from the Foreman console then you need to use `ComputeResource` as one word.

**Comment by eevans6913** [comment]
Originally I installed fog-hyperv irnoring dependencies. I install “gem install fog-hyperv”.

 

Now here is the result. 

***@***.*** ~]# foreman-rake console

[fog][DEPRECATION] Unable to load Fog::Hyperv::Compute

[fog][DEPRECATION] Falling back to deprecated constant Fog::Compute::Hyperv. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format.

Loading production environment (Rails 6.0.3.4)

irb(main):001:0> cr = ComputeResource.find_by name: 'HV01'

=> #<ForemanHyperv::Hyperv id: 1, name: "HV01", description: "", url: "http://hv01.digitaldatatechs.com/wsman", user: "digitaldatatech\\Administrator", password: [FILTERED], uuid: nil, type: "ForemanHyperv::Hyperv", created_at: "2021-06-24 16:49:50", updated_at: "2021-06-24 16:49:50", attrs: {}, caching_enabled: true, domain: nil, http_proxy_id: nil>

irb(main):002:0> cr.vms

[fog][DEPRECATION] Unable to load Fog::Hyperv::Compute

[fog][DEPRECATION] Falling back to deprecated constant Fog::Compute::Hyperv. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format.

Traceback (most recent call last):

        1: from lib/tasks/console.rake:5:in `block in <top (required)>'

WinRM::WinRMHTTPTransportError (Unable to parse authorization header. Headers: {"Content-Type"=>"text/html; charset=us-ascii", "Server"=>"Microsoft-HTTPAPI/2.0", "Date"=>"Fri, 25 Jun 2021 12:45:42 GMT", "Connection"=>"close", "Content-Lengt)"=>"315"}

Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">

<HTML><HEAD><TITLE>Not Found</TITLE>

<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>

<BODY><h2>Not Found</h2>

<hr><p>HTTP Error 404. The requested resource is not found.</p>

</BODY></HTML>

(404).

I’m not sure how to change the service provider, but it looks like fog-hyperv is not being initialized properly.

Also, selinux and firewall is disabled for testing purposes.

It is finding the hyperv hosts, but still an issue with wsman. 

Any help is appreciated.

 

Eric Evans

304.660.9080

Digital Data Services LLC

digitaldatatechs.com

**Comment by eevans6913** [comment]
So far, I can find the hyper-v hosts, but cr.vms still fails.

Foreman-rake console works but gives this warning:

Falling back to deprecated constant Fog::Compute::Hyperv. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format. And when I type cr.vms I get the same message then the error:

Traceback (most recent call last):

        1: from lib/tasks/console.rake:5:in `block in <top (required)>'

WinRM::WinRMHTTPTransportError (Unable to parse authorization header. Headers: {"Content-Type"=>"text/html; charset=us-ascii", "Server"=>"Microsoft-HTTPAPI/2.0", "Date"=>"Fri, 25 Jun 2021 14:11:58 GMT", "Connection"=>"close", "Content-Lengt)"=>"315"}

Body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">

<HTML><HEAD><TITLE>Not Found</TITLE>

<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>

<BODY><h2>Not Found</h2>

<hr><p>HTTP Error 404. The requested resource is not found.</p>

</BODY></HTML>

(404).

 

Thanks for your help. It is appreciated.

 

Eric Evans

304.660.9080

Digital Data Services LLC

digitaldatatechs.com

**Comment by eevans6913** [comment]
I got the issue resolved. Instead of using port 80 for compatibility, it used port 5985. I had tried it originally, but I assume my config was wrong on Hyper-V.

Thank you for your time and the work you do on projects to make our lives managing easier.

Take care.

 

Eric Evans

304.660.9080

Digital Data Services LLC

digitaldatatechs.com

**Comment by ananace** [comment]
Glad to hear you managed to get it resolved.
