### ISSUE TITLE
Issue with Gen2 Compute profiles

### ISSUE THREAD

**Issue by ksagle77** [ace13/foreman_hyperv#8]
Hey,

I'm running in to an issue when creating a Gen2 compute profile. I am able to create the a gen 2 profile:

![compute_profile](https://user-images.githubusercontent.com/34070189/33334071-8986d120-d41d-11e7-86ed-936769cec329.PNG)

but then once I try to open the profile, I get the following error:

Oops, we're sorry but something went wrong Hyper-V was unable to find a virtual machine with name "foreman_1511888691".
![image](https://user-images.githubusercontent.com/34070189/33334157-e233267a-d41d-11e7-9702-097081eb5409.png)
![image](https://user-images.githubusercontent.com/34070189/33334214-fd7ce056-d41d-11e7-82a5-a9a64e8f3e37.png)

![compute_profile_2](https://user-images.githubusercontent.com/34070189/33334072-89970022-d41d-11e7-91a3-6ed132798fd2.PNG)

The name 'foreman_1511888691' is static, it does not change based on the name of the profile/host/etc.

I looked for that string in the code, but was unable to find it. Stack trace is attached.

[stack_trace_compute.txt](https://github.com/ace13/foreman_hyperv/files/1510951/stack_trace_compute.txt)

Kevin

**Comment by ksagle77** [comment]
Note, I am able to create a gen 2 vm successfully using fog hyper-v directly.

vm = compute.new_vm(
  name: 'fogtest',
  generation: 2,
  path: 'd:\\newvms\fogtest',
  bootdevice: 'VHD',
  vhdpath: 'd:\\newvms\\fogtest\\fogtest.vhdx'
)
![image](https://user-images.githubusercontent.com/34070189/33334515-ffa1b194-d41e-11e7-8595-ff967ff06f52.png)

**Comment by ksagle77** [comment]
-bash-4.2$ gem list | grep fog-hyperv
fog-hyperv (0.0.5)

**Comment by ace13** [comment]
Then that's not the issue I'm thinking of.

Can you give me the Foreman version as well, and I'll throw up an environment for that when I'm back at my workstation.

**Comment by ksagle77** [comment]
rpm -qa '*foreman*' || dpkg -l '*foreman*' | sort

foreman-1.15.6-1.el7.noarch
tfm-rubygem-hammer_cli_foreman-0.10.2-1.el7.noarch
foreman-debug-1.15.6-1.el7.noarch
foreman-proxy-1.15.6-1.el7.noarch
foreman-cli-1.15.6-1.el7.noarch
foreman-installer-1.15.6-2.el7.noarch
foreman-selinux-1.15.6-1.el7.noarch
foreman-release-scl-3-1.el7.noarch
foreman-postgresql-1.15.6-1.el7.noarch
tfm-rubygem-foreman_setup-5.0.0-1.fm1_13.el7.noarch
foreman-release-1.15.6-1.el7.noarch

**Comment by ace13** [comment]
:+1: Thanks, I'll try and get back to you tomorrow once I've had time to test it out myself, see if I can replicate the bug.

**Comment by ksagle77** [comment]
Awesome, thanks! I'm trying to debug as well, but am fairly new to ruby. Do you have an idea on whether the issue would be in fog-hyperv, or foreman-hyperv?

**Comment by ace13** [comment]
I think it's most likely a foreman-hyperv issue, and I have a rather good idea what might be causing it as well.

Sadly don't have any of the things I need to try the changes out myself at hand.

**Comment by ksagle77** [comment]
Cool. If there's anything I can do to help, let me know.

**Comment by ace13** [comment]
As a quick hack just to see if my hypothesis holds any water, you could try applying the change from the commit I just pushed.

**Comment by ksagle77** [comment]
Awesome, the error no longer appears after applying those changes!

**Comment by ace13** [comment]
Great, then I'll have a starting point for making a proper fix once I'm in place and can test my code properly.

**Comment by ace13** [comment]
Fix is merged into master as of bfbb7afc8ffe48208d72714b33be2428370d8a50, closing this issue.
